version: "3"

networks: loki
services:
  loki:
    image: grafana/loki:2.4.2
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    restart: always

  promtail:
    image: grafana/promtail:2.4.2
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: always

  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3000:3000"
    networks:
      - loki
    restart: always
