version: '3.5'
# 网络配置
networks:
  backend:
    driver: bridge

# 服务容器配置
services:
  q:
    # 自定义容器名称
    container_name: chain
    build:
      context: ./service # 指定构建使用的 Dockerfile 文件
    volumes:
      # 设置挂载目录
      - /home/heco-docker/data:/root/data # 引用 .env 配置中 CODE_PATH_HOST 变量，将宿主机上代码存放的目录挂载到容器中 /usr/src/code 目录
    ports:
      # 设置端口映射  8545 8546 30303 30303/
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "32668:32668"
    stdin_open: true # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend
    restart: always # 指定容器退出后的重启策略为始终重启
